# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project.Our project Rescue is a responsive website to help women in panic and unsafe situations.
  Please adhere to our [Code of Conduct](https://github.com/swapnilsparsh/Rescue/blob/master/Code_of_Conduct.md).
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/swapnilsparsh/Rescue/blob/master/.github/pull_request_template.md).
  If you want to report a bugğŸ please follow our [Issue Template](https://github.com/swapnilsparsh/Rescue/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„
  
  Feel free to join our [Discord Community](https://discord.gg/FYz6cXQA).ğŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ğŸ˜„
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.Our project Rescue is a responsive website to help women in panic and unsafe situations.
  Please make sure you have followed our [Contributing Guidelines](https://github.com/swapnilsparsh/Rescue/blob/master/Contributing.md).ğŸ™ŒğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
  Feel free to join our [Discord Community](https://discord.gg/FYz6cXQA).ğŸ’– We have different channels for active discussions.âœ¨ Hope you have a great time there!ğŸ˜„
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.
